### ISSUE TITLE
retry of successful recursive copy fails.

### ISSUE THREAD

**Issue by jti-lanl** [pftool/pftool#11]
[cleaned up]
[latest cpp branch, plus latest libmarfs, etc.]

Seems reproducible.  Gets a '500 Internal Server Error' from Scality.  That could mean a lot of different things.  I saw that happen when we were failing to generate unique new object-names, for example.

[user@04 pftool]# mpirun -np 15 -H localhost installed/bin/pftool -s 16M -S 10G -C 10G -w 0 -r -p /source/1x10G/ -vv -c /dest
INFO  HEADER   ========================  TestJob  ============================
INFO  HEADER   Starting Path: /source/1x10G/
RANK   3: INFO  DATASTAT - drwxrwxr-x      8  19398  19398                  4096 Wed Mar 02 2016 10:38:58 /source/1x10G/
RANK   4: INFO  DATASTAT - -rw-rw-r--      0  19398  19398           10737418240 Wed Mar 02 2016 10:38:58 /source/1x10G/f01
RANK   3: INFO  DATACOPY Copied /source/1x10G/f01 offs 0 len 10737418240 to /dest/1x10G/f01
INFO  FOOTER   ========================   NONFATAL ERRORS = 0   ================================
INFO  FOOTER   =================================================================================
INFO  FOOTER   Total Files/Links Examined: 1
INFO  FOOTER   Total Dirs Examined: 1
INFO  FOOTER   Total Buffers Written: 1
INFO  FOOTER   Total Bytes Copied: 10737418240
INFO  FOOTER   Total Megabytes Copied: 10240
INFO  FOOTER   Data Rate: 75 MB/second
INFO  FOOTER   Elapsed Time: 134 seconds

[user@04 pftool]# mpirun -np 15 -H localhost installed/bin/pftool -s 16M -S 10G -C 10G -w 0 -r -p /source/1x10G/ -vv -c /dest
INFO  HEADER   ========================  TestJob  ============================
INFO  HEADER   Starting Path: /source/1x10G/
RANK   3: INFO  DATASTAT - drwxrwxr-x      8  19398  19398                  4096 Wed Mar 02 2016 10:38:58 /source/1x10G/
RANK   4: INFO  DATASTAT - -rw-rw-r--      0  19398  19398           10737418240 Wed Mar 02 2016 10:38:58 /source/1x10G/f01
RANK   3: ERROR NONFATAL: /dest/1x10G/f01: wrote -1 bytes instead of 16777216 (Input/output error, curl: '500 Internal Server Error')
RANK   3: ERROR NONFATAL: Failed to close dest file: /dest/1x10G/f01 (Connection timed out)
INFO  FOOTER   ========================   NONFATAL ERRORS = 2   ================================
INFO  FOOTER   =================================================================================
INFO  FOOTER   Total Files/Links Examined: 1
INFO  FOOTER   Total Dirs Examined: 1
INFO  FOOTER   Total Buffers Written: 0
INFO  FOOTER   Total Bytes Copied: 0
INFO  FOOTER   Elapsed Time: 32 seconds

**Comment by cadejager** [comment]
I fixed this by unlinking files before we try to write to them the first time. This fix however needs to be changed in the future to allow for partial restarts.

**Comment by brettkettering** [comment]
I'm a bit concerned about "fixing" something that's not really fixed. I'm afraid this knowledge will get lost in the future. If there's a valid reason for not fixing it all the way, create another issue and document extensively in the code the need for the future fix enhancement.

Thanks,
Brett

________________________________

**Comment by thewacokid** [comment]
At this point we're trying to bug squash enough to make it through Open Science. It's not ideal, but solves the short term need of being able to overwrite files that fail to complete.

- Dave

Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.
From: Brett Kettering
Sent: Monday, March 28, 2016 8:35 PM
To: pftool/pftool
Reply To: pftool/pftool
Subject: Re: [pftool/pftool] retry of successful recursive copy fails. (#11)


I'm a bit concerned about "fixing" something that's not really fixed. I'm afraid this knowledge will get lost in the future. If there's a valid reason for not fixing it all the way, create another issue and document extensively in the code the need for the future fix enhancement.

Thanks,
Brett

________________________________

**Comment by thewacokid** [comment]
Digging on this, it appears to still pop up when copying with "-n" for N:1 files but in a different manner.  It still compares improperly (haven't dug into why yet) but when it tries to overwrite, it complains about the inability to truncate the output file.

[dbonnie@fta01 ~]$ pfcp -vn /lustre/scratch/dbonnie/bigfile1.test2 /campaign/admins/dbonnie/
"/users/dbonnie" pfcp -vn /lustre/scratch/dbonnie/bigfile1.test2 /campaign/admins/dbonnie/
ranks = 15
manager: creating temp_path /campaign/admins
INFO  HEADER   ========================  dbonnie557153132016fta04.localdomain  ============================
INFO  HEADER   Starting Path: /lustre/scratch/dbonnie/bigfile1.test2
RANK   3: INFO  DATASTAT - -rw-rw-r-- 8192008  14697  14697            4194304000 Fri Mar 25 2016 14:25:00 /lustre/scratch/dbonnie/bigfile1.test2
RANK   7: INFO  DATACOPY Copied /lustre/scratch/dbonnie/bigfile1.test2 offs 3221216643 len 973087357 to /campaign/admins/dbonnie/bigfile1.test2
RANK   5: INFO  DATACOPY Copied /lustre/scratch/dbonnie/bigfile1.test2 offs 1073738881 len 1073738881 to /campaign/admins/dbonnie/bigfile1.test2
RANK   4: INFO  DATACOPY Copied /lustre/scratch/dbonnie/bigfile1.test2 offs 0 len 1073738881 to /campaign/admins/dbonnie/bigfile1.test2
RANK   6: INFO  DATACOPY Copied /lustre/scratch/dbonnie/bigfile1.test2 offs 2147477762 len 1073738881 to /campaign/admins/dbonnie/bigfile1.test2
INFO  FOOTER   ========================   NONFATAL ERRORS = 0   ================================
INFO  FOOTER   =================================================================================
INFO  FOOTER   Total Files/Links Examined: 1
INFO  FOOTER   Total Dirs Examined: 0
INFO  FOOTER   Total Buffers Written: 4
INFO  FOOTER   Total Bytes Copied: 4194304000
INFO  FOOTER   Total Megabytes Copied: 4000
INFO  FOOTER   Data Rate: 250 MB/second
INFO  FOOTER   Elapsed Time: 15 seconds
Launched /opt/campaign/pftool/installed/bin/pfcp from host fta04.localdomain at: Thu Mar 31 09:57:06 MDT 2016
Job finished at: Thu Mar 31 09:57:23 MDT 2016
[dbonnie@fta01 ~]$ pfcp -vn /lustre/scratch/dbonnie/bigfile1.test2 /campaign/admins/dbonnie/
"/users/dbonnie" pfcp -vn /lustre/scratch/dbonnie/bigfile1.test2 /campaign/admins/dbonnie/
ranks = 15
manager: creating temp_path /campaign/admins
INFO  HEADER   ========================  dbonnie2657153132016fta04.localdomain  ============================
INFO  HEADER   Starting Path: /lustre/scratch/dbonnie/bigfile1.test2
**couldn't truncate file '/campaign/admins/dbonnie/bigfile1.test2': Permission denied**
RANK   3: INFO  DATASTAT - -rw-rw-r-- 8192008  14697  14697            4194304000 Fri Mar 25 2016 14:25:00 /lustre/scratch/dbonnie/bigfile1.test2
RANK   7: ERROR NONFATAL: Failed to close dest file: /campaign/admins/dbonnie/bigfile1.test2 (Input/output error, curl: '500 Internal Server Error')
RANK   5: ERROR NONFATAL: /campaign/admins/dbonnie/bigfile1.test2: wrote -1 bytes instead of 16774273 (Input/output error, curl: '500 Internal Server Error')
RANK   4: ERROR NONFATAL: /campaign/admins/dbonnie/bigfile1.test2: wrote -1 bytes instead of 16774273 (Input/output error, curl: '500 Internal Server Error')
RANK   6: ERROR NONFATAL: /campaign/admins/dbonnie/bigfile1.test2: wrote -1 bytes instead of 16774273 (Input/output error, curl: '500 Internal Server Error')
RANK   5: ERROR NONFATAL: Failed to close dest file: /campaign/admins/dbonnie/bigfile1.test2 (Connection timed out)
RANK   4: ERROR NONFATAL: Failed to close dest file: /campaign/admins/dbonnie/bigfile1.test2 (Connection timed out)
RANK   6: ERROR NONFATAL: Failed to close dest file: /campaign/admins/dbonnie/bigfile1.test2 (Connection timed out)
INFO  FOOTER   ========================   NONFATAL ERRORS = 7   ================================
INFO  FOOTER   =================================================================================
INFO  FOOTER   Total Files/Links Examined: 1
INFO  FOOTER   Total Dirs Examined: 0
INFO  FOOTER   Total Buffers Written: 0
INFO  FOOTER   Total Bytes Copied: 0
INFO  FOOTER   Elapsed Time: 33 seconds
Launched /opt/campaign/pftool/installed/bin/pfcp from host fta04.localdomain at: Thu Mar 31 09:57:26 MDT 2016
Job finished at: Thu Mar 31 09:58:01 MDT 2016

**Comment by brettkettering** [comment]
This too is related to #13 and #4.

**Comment by brettkettering** [comment]
Have some workarounds in place, but they don't solve the problem. Have some ideas on how to fix this problem. Need to replace workarounds with idea implementations and test.

**Comment by jti-lanl** [comment]
In the latest system, with N:1 restarts working, doing the unlink mentioned above has the effect (as Chris suggested) of trashing the chunk-objects written before the restart.

The restart then "succeeds", but the result (with newer marfs xattrs) is unreadable, because some of the objects (corresponding to chunks written before the restart) will be 404 Not Found.

**Comment by jti-lanl** [comment]
Fixed by having pftool take responsibility for calling Path::pre_process() only with paths that have already been unlinked.  This also means assuring that N:1 files being restarted (e.g. having some writes already) do not get sent to pre_process.

I couldn't get the patched version of pftool to call pre_process() with an existing file.  If that does happen, I believe we'll see (non-fatal) error from pftool, and it should skip working on that file.
