### ISSUE TITLE
Relative paths resolve incorrectly -

### ISSUE THREAD

**Issue by thewacokid** [pftool/pftool#15]
I don't have an exhaustive comparison of how paths are expanded, but they do seem to resolve improperly for special dirs like "." and ".." for source and destination.

I'll put in a pull request soon for the updates to the pfcp/pfcm/pfls scripts that launch pftool, I added an absolute path resolver in them so that pftool only has to deal with absolute paths (for now).  The assumption I had to make is that nobody will have "/var/lib/perceus/vnfs/" along with "/rootfs/" in their path.  I believe that's fairly safe, but I'm documenting it here just in case someone uses it outside of LANL and decides to Google.

**Comment by thewacokid** [comment]
Python fixed here: https://github.com/pftool/pftool/commit/95ddc325b548c01989c2c20e8bd3e6345050febf

**Comment by brettkettering** [comment]
This needs to be fixed at some point, but the pf* wrapper scripts now change relative paths to full paths. So, we can get by without fixing this for Secure Campaign because we'll only allow users to use these wrapper scripts.

**Comment by jti-lanl** [comment]
pftool could generate absolute paths by either (a) calling realpath(), or (b) simulating realpath() by prepending cwd and then canonicalizing using just regular expressions.

However, for marfs paths containing symlinks, the former approach would fail on back-end nodes where there was no marfs fuse-mount.  The latter approach would produce unexpected results for paths that include symlinks that refer to directories with parents that are different from the parent of the symlink.  (For example: "./my_dir_link/../blah" is not necessarily the same as "./blah".)

Rather than having pf-scripts do explicit string-processing on the paths, it seems like one simple and safe alternative would be for **pf-scripts to invoke realpath()**.  The nice thing about that approach is that those scripts run on the front-ends, with e.g. marfs_fuse mounted, so symlinks can be followed.

Another option is for **pftool to implement its own realpath(), using Path::readlink(), etc**.

**Comment by jti-lanl** [comment]
On second thought, there's more to be discussed here.

**Comment by jti-lanl** [comment]
Another issue is that pftool called from pf-scripts doesn't know what the working-dir was, when the pf-scripts were invoked.  This information could be passed as another argument to pftool, but it's starting to look easier to just call realpath() in the scripts.

**Comment by garygrider** [comment]
Seems like realpath in the scripts gets us pretty far

Is there a scriptable version of realpath or do we need to write a 4 line C program?

**Comment by thewacokid** [comment]
I already modified the pf-scripts to use abspath to get rid of weirdness with relative paths, switching that over to realpath would be very trivial (or a combination of both).

> 
> os.path.realpath(path) <https://docs.python.org/2/library/os.path.html#os.path.realpath>
> Return the canonical path of the specified filename, eliminating any symbolic links encountered in the path (if they are supported by the operating system).
> 
> New in version 2.2.
> 

- Dave

**Comment by thewacokid** [comment]
So, this popped up in production this week.  I need to test it, but DNE is creating headaches.  I used os.path.abspath in my patch, but not os.path.realpath.  The former does not resolve symlinks, and DNE uses symlinks to shuffle users around between metadata servers.  Pftool for whatever reason (I didn't dig into it) doesn't handle these directory symlinks properly.

Anyone see any problems with simply resolving symlinks prior to handing them to pftool?

**Comment by cadejager** [comment]
I think that will suffice for the next release. Leave the issue open so that we someone can actually dig into the pftool issue.

**Comment by cadejager** [comment]
This has been fixed by 5e4fe559ea9c5809c3033ba6f3c20b27770f3e49 in pftool proper.
