### ISSUE TITLE
delete file-CTM when destination doesn't exist

### ISSUE THREAD

**Issue by jti-lanl** [pftool/pftool#21]
Here's an example of a problematic scenario:

* run pftool on a non-existent destination
run long enough to save CTM ( >= 4 chunks for file-CTM)
ctl-C

* delete the destination (e.g. through fuse)

* run pftool again
run not long enough to save a new CTM file (< 4 chunks)
ctl-C

Now, the CTM file indicates the 4+ chunks originally written, though there are only the 2 new chunks actually written.  When you restart pftool yet again, it will resume writing where the CTM file says the last chunk was written, which would be at e.g. chunk 4+.  (Similar behavior happens if the first run writes e.g. 8, and the second run writes 4.  In other words, the problem doesn't depend on the second run stopping short of saving CTM.)

It looks like the fix for this would be to add a "purgeCTM(out_node.path)" in the early part of process_stat_buffer(), where it has learned that the destination doesn't exist, but before it starts actual processing.

[I have a patch for this, but I'm testing something else, first.]

**Comment by garygrider** [comment]
Indeed, there has to be some kind of date compare or something between the ctm entry and the dest file, maybe even more comparative info.
Maybe the inode+creationdate have to match and the CTM date needs to be later than creation or …
Keeping the restart info non on dest creates all sorts of issues, but it does work where there is no way to keep it with the dest.

Seems like you

a)      Have to know it’s the same file (inode+creation date)

b)      Have to know if the file has been modified since the ctm file was last updated.  I guess date compare and pray the dates of the nodes are synced well?

**Comment by jti-lanl** [comment]
I think the CTM file has to be allowed to be behind the date of the destination, because we only update the CTM-file every so often.

We're currently fixing things so that when the CTM is out-of-date, we handle the couple of write failures we get trying to write objects that were already written, but which the CTM file hasn't yet heard about.

For MarFS destinations, I think the only (legitimate) way for the CTM file to get into an illegal state is for someone to delete or truncate the destination entirely and start writing it again.   So, my proposed fix should also include the case where the destination does exist, but has length zero.

With POSIX destinations, a user could hurt themselves by truncating to non-zero (smaller than before), then trying the copy again.  They'd get a gap in their file.

So, a further improvement would be to guarantee that the destination is at least as big as the CTM file says it should be.  If not, we should probably punt the whole copy, with an error.  Either we failed to prevent that state from occurring, or the user is being very creative in trying to hurt themselves.

Does that sound right?

**Comment by garygrider** [comment]
I guess its full of holes no matter what.  The user can shoot himself.   We should just make sure our restarter does its best.
If the file is new (store inode /create date maybe) or if the file is smaller than it shoud be although since it is doen async, that wont tell us all that much
Because it isn’t copied sequentially but it is one more check of sanity.  I suppose if its bigger than it should be is ok as we might have gotten farther, etc.
The user could still shoot himself in the foot but I suppose that is always true with everything at some level

**Comment by jti-lanl** [comment]
If destination doesn't exist, or has size==0, then at least in these cases, we can purge any existing CTM.  This fixes the problematic example.
