### ISSUE TITLE
PFTool file copy retry flag

### ISSUE THREAD

**Issue by gsparrow** [pftool/pftool#38]
When copying large data with PFTool, either a large file or large numbers of files, PFTool often encounters non-fatal errors during the copy and not all data is copied. Since PFTool returns a non-zero exit code when this occurs, it would be nice if we could catch the exit status and retry the command a given number of times. Considerations need to be made for a low maximum, in the event that the command is incorrect, and what the default number of tries should be. This should likely be placed inside of the pfcp script.

**Comment by thewacokid** [comment]
Perhaps it would make sense to return a particular error code for a command that ran okay, minus a few missing holes.  Those can be safely retried without worry, while retrying a bad command can be filtered out.

**Comment by brettkettering** [comment]
We discussed this. The default should be one try because that's what pfcp does now. So, to have multiple tries before failure is declared one needs to explicitly use the parameter.

Regarding Dave's comment, we can certainly return different values, a la error.h, with a code that tells you if it failed because the command was incorrect or because you didn't finish the copy job before an error occurred.

**Comment by jti-lanl** [comment]
So, it sounds like maybe the presence of non-fatal errors should provoke a non-zero return code, while fatal errors should provoke a different code.
Maybe non-fatals return some positive value, while fatals return negative.  Or -1 and -2.  Or something.

**Comment by thewacokid** [comment]
I would think that invoking the "retry-able" flag, currently "-n", should indicate the user wants to have the transfer retry some reasonable number of times.

Honestly, I think we should make the "-n" the default.  I can't see any reason why a regular user wouldn't use it besides simply not knowing it exists.

**Comment by cadejager** [comment]
So these are the changes I see involved in this enhancement:

1. make -n the default mode for pfcp
2. make sure that fatal and non fatal errors return a different status.
3. Add a flag (default 1) to retry some number of times on non fatal errors.

**Comment by jti-lanl** [comment]
Seems like the retry on non-fatals might do best to wait until the whole pftool run had completed,
then retry that run.  Rather than immediately retrying each individual non-fatal error, because
they are already the result of internal retries, and if they are failing, it's probably because some
server is struggling under the load, and might do better with a cool-off.

Not sure about making -n be the default.  Wouldn't we then need some other option that would mean
"don't do the default thing".

**Comment by cadejager** [comment]
Making sure that fatal and non fatal errors don't return the same code is a change for pftool proper.

-n would just be the default mode for pfcp. retries would also be a pfcp change so yes pftool would complete a full run and then get restarted.
