### ISSUE TITLE
Restart on partial copy not working in cpp branch

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#4]
CTE does not seem to be working in the cpp branch. I am looking into why this is broken.

**Comment by cadejager** [comment]
This is related to the bug that was fixed where pftool did not call update_stats on chunked files if xattrs are not supported on the source file system. This appears to only effect the cpp branch.

**Comment by brettkettering** [comment]
This needs to be fixed before the chunk problem. It is closely related. Changing assignment.

**Comment by jti-lanl** [comment]
I think what Chris meant was CTM.

**Comment by brettkettering** [comment]
I'm going to record Gary Grider's comment on including chunk size in the partial restart file using $HOME/.pftool. I think it's a good thing if we can find a way that works for POSIX and MarFS. I think you should talk to David Sherrill too. Ultimately we need to bring the branches back together into a PFTool that works everywhere.

Considering that the ultimate plan is for files of very large scale the issue with the xattr getting so large that it isn't supported could become an issue. I wonder if there's any serious/performance/functional advantage to using xattrs on the dest file instead of simply using a hashed file in $HOME/.pftool. Eliminating the use of dest file xattrs removes what could become logic that could result in difficult-to-debug errors when the dest file system may or may not support xattrs and then may or may not support xattrs of the size we need to generate.

Here is Gary's comment:
So you say you hash the full dest path in a .pftool directory in the home directory.

Seems like you also need to record the chunk size the file was written with in the restart status file or maybe in the name of the file or something, otherwise if someone changes the chunk size in-between restarts you might get the wrong answer?

Seems like if we converge on this home dir file hashed on full dest path with chunk size recorded maybe it just works for all destinations.  Maybe we can make it easy and just have that one method, since using an xattr on the dest file may be dangerous since it might get to be pretty big 10s of k or megabyte which is large .  The marfs method of putting it in the mdfile will work but if we want to go back to just the one method using the hashed name in the home dir, that would be ok with me to keep it simple.

If home dir doesn’t work, then we fall back to using full file restart only for all files including big ones I guess.

Anyway, it just occurred to me that recording the chunk size in the restart status file makes sense because there are no xattrs on some destinations to record chunk size there.

**Comment by brettkettering** [comment]
David Sherrill sent me a message and noted that the requirement to keep chunksize for the transfer is already in the main branch implementation he did. He said that it was, indeed, obvious that it was required when he implemented the feature.

**Comment by brettkettering** [comment]
Related to #11 and #13. Time for implementation.

**Comment by jti-lanl** [comment]
This was fixed along with #13.

We now have a configure option for pftool:  '--enable-ctm=style'  where *style* can be one of { files | xattrs | no | }.  The default is files, which short-circuits _whichCTM() to always prefer files for N:1 chunk-info bits.  No changes to the rest of David's code (and the "xattrs" style does what David's code used to do).  After every 4 chunks, his code updates bits in a hashed file in ~/.pftool/chunkfiles.  Thus, when restarting (with "-n") after a partial write to an N:1 file, supposing you wrote k chunks, you'll start after the first k%4 chunks you completed.
