### ISSUE TITLE
Retries are noisy -

### ISSUE THREAD

**Issue by thewacokid** [pftool/pftool#69]
We should probably hide retries from the user unless the end result is an actual failure to copy data.  Perhaps they should only show in verbose mode?

**Comment by jti-lanl** [comment]
Fixed in e37da20.   Retries that ultimately result in failure (i.e. did our full allotment of retries and no joy) are reported to user, and syslog, as a single non-fatal error.  If you run with '-l', the retries that result in success (i.e. after some number of retries) will send a single message to syslog.  Search for "retries" in syslog to find both kinds of messages.
