### ISSUE TITLE
Order of Packed Obj. Xattr Operations Can Lead to GC Problems

### ISSUE THREAD

**Issue by gransom** [pftool/pftool#70]
It seems that when completing the write of a packed object into MarFS, pftool sets a POST xattr and removes RESTART from each file sequentially.  This should likely be changed to setting the POST for each file in sequence, then removing the RESTART for each file in sequence.
Currently, if pftool were killed partway through this process, this could lead to some files which are considered valid (POST and no RESTART) while others remain with no POST.
This leads to problems for MarFS garbage collection.  If a single file from the packed object is deleted and that file had no POST xattr, it will be given a POST xattr with a default "objs" value of 1.  This would cause the GC to wrongfully delete the entire packed object, removing the data out from under the files considered valid (no RESTART).

**Comment by jti-lanl** [comment]
Doesn’t the new way have the same limitation as the old (allowing RESTART w/out POST)?  Maybe for a shorter period of time.

Does it make sense for GC to assign a new POST with default values, in the case where an object has only RESTART?

(Actually, backing up, I thought pftool assigned both PRE and POST before writing.  Oh, but not for packed files, because it doesn’t have enough info.)  Still, the PRE should tell us that the trashed file is packed, so GC could theoretically go through the painful process of groveling the actual object, looking at recovery info, to find which files are in it.  (I think there are some functions in libmarfs that could help.)  That file-MD from recovery-info could be out of date, with respect to file name/location — members of the packed object could have been moved — but we would at least have their inode-numbers, associated with the packed file.  I think this means we could track the incomplete packed file-inodes encountered by GC, associated with each packed object, along with the complete ones we already track.

The size of this list could potentially exceed the size of memory, which complicates sorting.  Instead, we could keep distinct sub-lists in distinct files (e.g. hashed by packed-file inode, or something).  Then these can be sorted, the number of entries tallied, and either (a) delete the packed-file and all its files (if they are all in trash), or (b) at least update the POST xattrs for all the members that didn’t have one.  (But maybe that won’t be needed anytime soon, as pftool shouldn’t be frequently crashing in the middle of writing packed files?)

We can’t just delete the incomplete member file, because then any completed survivors will never detect that they have all been trashed, since they all have POST with objs=N.  The recovery-groveling exercise potentially allows a way out of this, by adjusting the POST of all the surviving members, but probably not worth it.

**Comment by cadejager** [comment]
@wfvining, @gransom, I were talking and have come up with the following two solutions.

1. Rewrite pftool to first set the correct post xattr for every file in the object and then clear the restart xattr.

2. Make the garbage collector not use the objs xattr. This would be done by getting at the size of the data object from the manifest file and then seeing if the total size of the files in the trash add up to that size.

Option 2 is currently the way we are leaning because we think it will make marfs easier to interface with in the future and simplifies the xattrs.

**Comment by jti-lanl** [comment]
I think I get this, now.  I was thinking you had already worked out a way, with the approach @gransom described, to allow deleting the incomplete members of a packed object, if they are found in the trash.  But, on second thought, I guess that left a problem if other members are later deleted, especially if any of them are completed.  I like your new scheme (option 2) of looking at the object length.  That’s cheaper than groveling the recovery info.  Option 1 seems like it might allow for cheaper future assessments, when running GC again and again on the same partially-deleted packed object, but at the cost of some extra effort up front.

**Comment by cadejager** [comment]
https://github.com/mar-file-system/marfs/commit/c1d4697b3cca671c4ae0ab849ec9a6b1027c02f3 was also part of this fix.
